spring.application.name=clientManager

spring.datasource.url=jdbc:h2:mem:clientManagerDB
spring.datasource.driverClass=org.h2.Driver
spring.datasource.usernam=sa
spring.datasource.password=
spring.h2.console.enabled=true
